
color murphy
"color evening

set nu
set history=680
set autoread

set so=8
set wildmenu
set ruler
set wildignore=*.o,*~,*.pyc
set cmdheight=2
set hid
set backspace=eol,start,indent
set ignorecase
set smartcase
set hlsearch
set incsearch
set lazyredraw
set magic
set showmatch
set mat=2
set noerrorbells
set novisualbell
set t_vb=
set tm=500

set ffs=unix,dos,mac

set nobackup
set nowb
set noswapfile

set expandtab
set smarttab
set shiftwidth=2
set tabstop=2

set lbr
set tw=500
set ai 
set si
set wrap



